name: Run AI Chat on Messenger Account (standalone)

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Input Facebook username (email/phone)"
        required: true
      password:
        description: "Input Facebook password (optional)"
        required: false
      otp_secret:
        description: "Input App authenticator OTP Secret (optional)"
        required: false
      onetimecode:
        description: "Input one-time code to decrypt p2p chat (optional)"
        required: false
      alt_account:
        description: "Input the index of account if the Facebook account has multiple accounts, 0 for main account"
        default: "0"
        required: false
      cookies_text:
        description: "Input cookies (optional)"
        required: false
      ai_prompt:
        description: "Input the persona introduction for AI instruction (optional, refer to setup/introduction.txt)"
        required: false
      gemini_key:
        description: "Input the Gemini API Key (obtain from [https://aistudio.google.com/app/apikey])"
        required: true
      work_jobs:
        description: "Type one or more of these options: (aichat[=normal|devmode],friends,autolike,keeponline)"
        required: false
        default: "aichat=normal,friends"
      run_aichat:
        description: "Run AI Chat, untick to check login only"
        required: false
        default: "true"
        type: boolean

jobs:
  run-aichat:
    runs-on: windows-latest
    timeout-minutes: 300
    env:
      SCPDIR: ${{ github.workspace }}\scoped_dir
      COOKIESFILE: ${{ github.workspace }}\cookies.json
      FBINFOSFILE: ${{ github.workspace }}\facebook_infos.bin
      SELF_FBINFOFILE: ${{ github.workspace }}\self_facebook_info.bin
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass GitHub Token
      GITHUB_REPO: ${{ github.repository }}     # Pass the repository (owner/repo)
      STORAGE_BRANCE: caches/manual/${{ inputs.username }}/${{ inputs.alt_account || '0' }}

    steps:
      # Checkout the repository
      - name: Checkout HuskyDG Automatic FB
        uses: actions/checkout@v3
        with:
          repository: HuskyDG/automatic_fb
          ref: main # Optional: main or tags name

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Test selenium
      - name: Test selenium
        run: |
          python test_selenium.py
        env:
          PYTHONUNBUFFERED: "1"

      # Login to Facebook account
      - name: Login Facebook account
        run: |
          python fb_getcookies_test.py
        env:
          PYTHONUNBUFFERED: "1"
          USE_ENV_SETUP: "true"
          PASSWORD: ${{ secrets.PASSWORD }} # Decrypt key

      # Run AI chat script (conditionally)
      - name: Run AI Chat script
        if: ${{ inputs.run_aichat == true }}
        run: |
          python aichat_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          GENKEY: ${{ inputs.gemini_key }}