name: Run AI Chat on Messenger account (schedule)

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  run-aichat:
    runs-on: windows-latest
    timeout-minutes: 310

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script
      - name: Login Facebook account
        run: |
          python secrets/decrypt.py
          python fb_getcookies_test.py
        env:
          PYTHONUNBUFFERED: "1"
          PASSWORD: ${{ secrets.PASSWORD }}
          USE_ENV_SETUP: "false"

      # Conditionally cancel previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Run the script
      - name: Run script
        run: |
          python aichat_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          GENKEY: ${{ secrets.GENKEY }}
          PASSWORD: ${{ secrets.PASSWORD }}
