name: Run AI Chat on Messenger account

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
    inputs:
      username:
        description: "Input facebook username (email/phone)"
        required: true
      password:
        description: "Input facebook password"
        required: true
      otp_secret:
        description: "Input App authenticator OTP Secret (optional)"
        required: false
      alt_account:
        description: "Input the index of account if the facebook account has multiple accounts, 0 for main account"
        default: "0"
        required: false
      ai_prompt:
        description: "Input the AI behavior prompt (optional)"
        required: false
      cancel-workflow:
        description: "Cancel previous workflow runs (default true)"
        required: false
        default: "true"
        type: boolean  # Chỉ định loại dữ liệu là boolean

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 310

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script
      - name: Login Facebook account
        if: ${{ github.event_name == 'schedule' }}
        run: |
          python logininfo_unzip.py
          python fb_getcookies_test.py
        env:
          PYTHONUNBUFFERED: "1"
          PASSWORD: ${{ secrets.PASSWORD }}
          USE_ENV_SETUP: "false"

      - name: Login Facebook account
        if: ${{ github.event_name != 'schedule' }}
        run: |
          python fb_getcookies_test.py
        env:
          PYTHONUNBUFFERED: "1"
          USE_ENV_SETUP: "true"
          USERNAME: ${{ inputs.username }}
          PASSWORD: ${{ inputs.password }}
          OTP_SECRET: ${{ inputs.otp_secret || '' }}
          ATL_ACC: ${{ inputs.alt_account || '0' }}

      # Conditionally cancel previous runs
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'schedule' || inputs.cancel-workflow == true }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Run the script
      - name: Run script
        run: |
          python aichat_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          GENKEY: ${{ secrets.GENKEY }}
          AI_PROMPT: ${{ inputs.ai_prompt || '' }}
