name: Run AI Chat on Messenger account

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
    inputs:
      cookies:
        description: "Input the cookies value (optional)"
        required: false
      ai_prompt:
        description: "Input the AI prompt (optional)"
        required: false
      cancel-workflow:
        description: "Cancel previous workflow runs (default true)"
        required: false
        default: "true"
        type: boolean  # Chỉ định loại dữ liệu là boolean

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 310

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Conditionally cancel previous runs
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'schedule' || inputs.cancel-workflow == true }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Run the script
      - name: Run script
        run: |
          python aichat_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          COOKIES: ${{ inputs.cookies || secrets.MYCOOKIES }}
          GENKEY: ${{ secrets.GENKEY }}
          AI_PROMPT: ${{ inputs.ai_prompt || '' }}
