name: Run test_cookies.py

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 310

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Cache Python dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/run-tests.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow selenium google-generativeai webdriver-manager pytz

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Run the script
      - name: Run script
        run: |
          git lfs pull
          python aichat_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          COOKIES: ${{ secrets.MYCOOKIES }}
          GENKEY: ${{ secrets.GENKEY }}
          PASSWORD: ${{ secrets.PASSWORD }}
