name: Run Auto Traodoisub with Facebook

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 130

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Conditionally cancel previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Run the script
      - name: Run script
        run: |
          python secrets/decrypt.py
          python traodoisub_v2_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          PASSWORD: ${{ secrets.PASSWORD }}
          TDS_TOKEN: ${{ secrets.TDS_TOKEN }}
